architect:
  - emilianodellacasa
install: |-
  sudo apt-get -y install python3 python3-dev python3-venv
  python3 -m venv venv
  . venv/bin/activate
  pip install -r requirements.txt
  sudo gem install pdd
  chmod +x install_db.sh
  ./install_db.sh
merge:
  script: |-
    chmod +x ./checkstyle.sh
    ./checkstyle.sh
    python check_pylint.py
    pytest -vv
    pdd -f /dev/null -v
deploy:
  script: |-
    chmod +x ./deploy.sh
    ./deploy.sh 
release:
  script: |-
    echo "There is nothing to release"
    exit -1

