architect:
  - emilianodellacasa
install: |-
  sudo apt-get -y install python3 python3-dev python3-venv
  python3 -m venv venv
  . venv/bin/activate
  pip install -r requirements.txt
  sudo gem install pdd
merge:
  script: |-
    pytest
    pdd -f /dev/null -v
    if grep -n \'.*\' ./timeless/*/*.py; then
        echo "Single-quotes are forbidden in .py files!"
        grep -n \'.*\' ./timeless/*/*.py
        exit 2;
    fi
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
release:
  script: |-
    echo "There is nothing to release"
    exit -1

