language: python
services:
  - postgresql
  - redis-server
python:
  - "3.6.7"
install:
  - pip install -r requirements.txt
  - gem install pdd
before_script:
  - psql -c "CREATE USER timeless_user WITH 
      SUPERUSER
      CREATEDB
      CREATEROLE
      INHERIT
      LOGIN
      ENCRYPTED PASSWORD 'timeless_pwd';" -U postgres
  - psql -c 'CREATE DATABASE timelessdb_test;' -U postgres
script:
  - pdd -f /dev/null
  - python checkstyle.py
  - python check_pylint.py
  - pytest --cov=./timeless
  - codecov --token=9110359e-20f8-46a4-872c-cd31cc35da00